### ISSUE TITLE
Fresh install Ubuntu 21.10 - Flasher fails to run.

### ISSUE THREAD

**Issue by TechCowboy** [FujiNetWIFI/fujinet-flasher#2]
Low priority, informational only

![Screenshot from 2021-10-21 18-05-39](https://user-images.githubusercontent.com/2847372/138356664-22f24533-146f-4132-888c-390f11877ec6.png)

**Comment by mozzwald** [comment]
Flasher for Ubuntu 21.10 is available at https://fujinet.online/firmware/FujiNet-Flasher/FujiNet-Flasher_Ubuntu-21.10.tar.bz2
