### ISSUE TITLE
Clear log window

### ISSUE THREAD

**Issue by XeAtari** [FujiNetWIFI/fujinet-flasher#7]
Hi,

when debugging or testing something I'ld like to have only the specific part for this action in the log window instead of searching through everything what is there to find the relevant part.

Now I was told just to push the -Serial Debug Output- button again which should clear the window.

Funnily enough it does, but the flasher also tries to open the COM port again while he did not disconnect it before.

Following error message appears:

Unexpected error: could not open port 'COM7': PermissionError(13, 'Zugriff verweigert', None, 5)

and of course things do not work any more. I have to close the flasher application and open it again.

OS: MS Windows

XeAtari

**Comment by mozzwald** [comment]
Can you test the attached build and let me know if this is still an issue for you? On my windows 11 system I get the "could not open port" error, but serial debug output is printed

[FujiNet-Flasher_win-x64.zip](https://github.com/FujiNetWIFI/fujinet-flasher/files/15477692/FujiNet-Flasher_win-x64.zip)

**Comment by mozzwald** [comment]
Latest release adds some serial port closing fixes https://github.com/FujiNetWIFI/fujinet-flasher/releases/tag/v1.4.2

Please reopen if it's still a problem
