### ISSUE TITLE
ability to flash wled bin files

### ISSUE THREAD

**Issue by Tom-Neverwinter** [FujiNetWIFI/fujinet-flasher#8]
I miss esphome. it was really easy to use and didnt suck like the new webflasher. 

can you add support for wled

**Comment by mozzwald** [comment]
This flasher is modified for use with Fujinet. If you want to flash some other random esp32 board with it's own custom firmware you can. You will need to create a json file that contains the list of firmware files/partitions and their offset in flash. The json and firmware files should be in a ZIP file which can be selected in FujiNet-Flasher. You can see an example firmware/json zip by grabbing the lastest FujiNet firmware from https://github.com/FujiNetWIFI/fujinet-firmware/releases/tag/nightly

We will not add specific support for any hardware besides FujiNet hardware to this repo, but you are welcome to fork and modify it to your needs.
